# Generated by Django 3.1.7 on 2021-05-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_20210503_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_description',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
